sudo: required
dist: xenial

language: node_js
node_js: 12

services:
  - docker

os:
  - linux
  # - osx

install:
  - yarn
  - yarn global add lix haxe-travix
  - lix download
  - docker run -d --name fakesmtp -p 1025:25 -v /tmp/fakemail:/var/mail digiplant/fake-smtp

script:
  - lix run travix node
